[PATCH] linux-user: Add missing mmap include
https://lore.kernel.org/qemu-devel/20241028181821.1440988-1-venture@google.com

---

From: Patrick Leis <venture@google.com>
To: laurent@vivier.eu, peter.maydell@linaro.org
Cc: qemu-devel@nongnu.org, Peter Foley <pefoley@google.com>,
 Patrick Leis <venture@google.com>
Content-Type: text/plain; charset="UTF-8"
Received-SPF: pass client-ip=2607:f8b0:4864:20::1149;
 envelope-from=3c9UfZwcKCtwTCLRSPCEMMEJC.AMKOCKS-BCTCJLMLELS.MPE@flex--venture.bounces.google.com;
 helo=mail-yw1-x1149.google.com
X-Spam_score_int: -95
X-Spam_score: -9.6
X-Spam_bar: ---------
X-Spam_report: (-9.6 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_MED=-0.001,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001, SPF_PASS=-0.001,
 USER_IN_DEF_DKIM_WL=-7.5 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

From: Peter Foley <pefoley@google.com>

error: use of undeclared identifier 'MAP_FIXED_NOREPLACE'

Signed-off-by: Patrick Leis <venture@google.com>
Signed-off-by: Peter Foley <pefoley@google.com>
---
 linux-user/user-mmap.h | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/linux-user/user-mmap.h b/linux-user/user-mmap.h
index b94bcdcf83..de769f9253 100644
--- a/linux-user/user-mmap.h
+++ b/linux-user/user-mmap.h
@@ -18,6 +18,8 @@
 #ifndef LINUX_USER_USER_MMAP_H
 #define LINUX_USER_USER_MMAP_H

+#include "linux/mman.h"
+
 /*
  * Guest parameters for the ADDR_COMPAT_LAYOUT personality
  * (at present this is the only layout supported by QEMU).
--
2.47.0.163.g1226f6d8fa-goog

Signed-off-by: GitHub Actions Bot <bot@github.com>