tests/tcg: Skip syscall catchpoint test if pipe2() syscall not available
Avoid the following errors testing i386 and ppc64:

  $ make check-tcg
  ...
    TEST    hitting a syscall catchpoint on i386
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-i386: QEMU: Terminated via GDBstub
  ...
    TEST    hitting a syscall catchpoint on ppc64
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-ppc64: QEMU: Terminated via GDBstub
  ...
    TEST    hitting a syscall catchpoint on ppc64le
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-ppc64le: QEMU: Terminated via GDBstub
  make: Target 'check-tcg' not remade because of errors.

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>