[PATCH RESEND] scripts/analyze-migration: Make it work in Python 3
https://lore.kernel.org/qemu-devel/20251124164439.67948-1-pzmarzly0@gmail.com

---

From: Pawel Zmarzly <pzmarzly0@gmail.com>
To: qemu-devel@nongnu.org
Cc: jsnow@redhat.com,
	michel@michel-slm.name
Subject: [PATCH RESEND] scripts/analyze-migration: Make it work in Python 3
Date: Mon, 24 Nov 2025 16:44:39 +0000
Message-ID: <20251124164439.67948-1-pzmarzly0@gmail.com>
X-Mailer: git-send-email 2.52.0
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2a00:1450:4864:20::429;
 envelope-from=pzmarzly0@gmail.com; helo=mail-wr1-x429.google.com
X-Spam_score_int: -17
X-Spam_score: -1.8
X-Spam_bar: -
X-Spam_report: (-1.8 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 FREEMAIL_ENVFROM_END_DIGIT=0.25, FREEMAIL_FROM=0.001,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-Mailman-Approved-At: Mon, 24 Nov 2025 12:56:09 -0500
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Currently crashing on Python 3 with:

    $ scripts/analyze-migration.py -m -f vm.state
    TypeError: ord() expected string of length 1, but int found

Signed-off-by: Pawel Zmarzly <pzmarzly0@gmail.com>
---
 scripts/analyze-migration.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/scripts/analyze-migration.py b/scripts/analyze-migration.py
index 67631ac43e..3303c05358 100755
--- a/scripts/analyze-migration.py
+++ b/scripts/analyze-migration.py
@@ -56,7 +56,7 @@ def readvar(self, size = None):
         if size is None:
             size = self.read8()
         if size == 0:
-            return ""
+            return b""
         value = self.file.read(size)
         if len(value) != size:
             raise Exception("Unexpected end of %s at 0x%x" % (self.filename, self.file.tell()))
@@ -200,7 +200,7 @@ def read(self):
                     self.files[self.name].seek(addr, os.SEEK_SET)
                     self.files[self.name].write(data)
                 if self.dump_memory:
-                    hexdata = " ".join("{0:02x}".format(ord(c)) for c in data)
+                    hexdata = " ".join("{0:02x}".format(c) for c in data)
                     self.memory['%s (0x%016x)' % (self.name, addr)] = hexdata

                 flags &= ~self.RAM_SAVE_FLAG_PAGE
--
2.51.1

Signed-off-by: GitHub Actions Bot <bot@github.com>