docs: fix docs/sphinx/qapi_domain.py error
FAILED: docs/docs.stamp
/usr/bin/env CONFDIR=etc/qemu /home/user/.work/qemu/build/pyvenv/bin/sphinx-build -q -W -Dkerneldoc_werror=1 -j auto -Dversion=10.0.50 -Drelease= -Ddepfile=docs/docs.d -Ddepfile_stamp=docs/docs.stamp -b html -d /home/user/.work/qemu/build/docs/manual.p /home/user/.work/qemu/docs /home/user/.work/qemu/build/docs/manual

Exception occurred:
  File "/home/user/.work/qemu/docs/sphinx/qapi_domain.py", line 250, in split_fqn
    module, name = name.split(".")
    ^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
The full traceback has been saved in /tmp/sphinx-err-4zq03_sl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ninja: build stopped: subcommand failed.

Signed-off-by: Pierrick Bouvier <pierrick.bouvier@linaro.org>