[PATCH v2] rust/wrapper.h: define memory_order enum
https://lore.kernel.org/qemu-devel/20241027-rust-wrapper-stdatomic-v2-1-dab27bbf93ea@linaro.org

---

From: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
Date: Sun, 27 Oct 2024 15:57:06 +0200
Subject: [PATCH v2] rust/wrapper.h: define memory_order enum
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Message-Id: <20241027-rust-wrapper-stdatomic-v2-1-dab27bbf93ea@linaro.org>
X-B4-Tracking: v=1; b=H4sIALFGHmcC/4WNQQ6CMBBFr0JmbU1ngARdeQ/DorYFJlFKphU1p
 He3cgGX7yX//Q2iF/YRztUG4leOHOYCdKjATmYevWJXGEhTgxpbJc+Y1EvMsnhRMTmTwoOtws6
 1HZ3IUlNDGS/iB37v4WtfeOKYgnz2nxV/9m9yRYVqILL65mrERl/uPBsJxyAj9DnnLzGE+tS9A
 AAA
X-Change-ID: 20241015-rust-wrapper-stdatomic-18d58292c243
To: qemu-devel@nongnu.org
Cc: =?utf-8?q?Alex_Benn=C3=A9e?= <alex.bennee@linaro.org>,
 =?utf-8?q?Daniel_P=2E_Berrang=C3=A9?= <berrange@redhat.com>,
 Gustavo Romero <gustavo.romero@linaro.org>,
 Junjie Mao <junjie.mao@hotmail.com>,
 =?utf-8?q?Marc-Andr=C3=A9_Lureau?= <marcandre.lureau@redhat.com>,
 Paolo Bonzini <pbonzini@redhat.com>,
 Peter Maydell <peter.maydell@linaro.org>,
 =?utf-8?q?Philippe_Mathieu-Daud=C3=A9?= <philmd@linaro.org>,
 Pierrick Bouvier <pierrick.bouvier@linaro.org>,
 Richard Henderson <richard.henderson@linaro.org>,
 Thomas Huth <thuth@redhat.com>
X-Mailer: b4 0.15-dev-12fc5
X-Developer-Signature: v=1; a=openpgp-sha256; l=3325;
 i=manos.pitsidianakis@linaro.org; h=from:subject:message-id;
 bh=LJFcZD5aGAm8omxYouCKWnkrDg4wDSrkse6NQ7L0waQ=;
 b=LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpvd0VCYlFLUy9aQU5Bd0FLQVhjcHgzQi9mZ
 25RQWNzbVlnQm5Ia2JDNCtJYmlQczlRaHd6eU80T0Z4UmtnWVJuCnZrS0Uwakh2Zmt0aDdKRTdi
 TGFKQWpNRUFBRUtBQjBXSVFUTVhCdE9SS0JXODRkd0hSQjNLY2R3ZjM0SjBBVUMKWng1R3dnQUt
 DUkIzS2Nkd2YzNEowRVBQRC85TnRtbG5RZWNaNVhtTFNsSlRTWnJ3NUVyOXVDcWhSNDBEQTRQMQ
 ptTWRDU3c1d1hQaVVPamZsb2Y2WXdMaWozRnNxN3VzdjdnMG42TytsaUVzQ0JnQ290azZlU2NWW
 XZCRjhkbDlzCmY5MXo0YWFjYXNpMEhueGxEMVZxUGxkK2ZPQjhoNDB0OE85N2x1c3FkY0FEZkdx
 U29oMVptYVYzSSt4NnR3SGQKT0RJNW5oTEE0SlVoMG5vY3NMY1dvd0JqY0lWVGI4Nm0zK1pFNDl
 1Nmc4TVJ3R0dvV3k1TThUbTFGVXJNOW0xTQozRFgrSTZuTG9GV0NTRHpBczl5U0d2UFNYUUM2dG
 lXeDhPRjBIZEZ2cWxpYytPeDRDVURZa2Q0WmNzWm51U1ZOClRFdDBTKzl4eWhHZWlPWUN2cm0wU
 Xd1eE5qWm5VYkZQbm1KaXpYK0pDOTQ0d3NiYjczcEZMVVlQNlVic0hRRDQKbGtEckhTU3VnaEM0
 OTRhdGNPNy9jZC9QS1pEQUtJWGdNR21WQmpkdU1QTVo4YXRtWnZwemdBWG1razRkUmJ2SQp5YlJ
 xVzVsdW5mMDdJejRZYnZ6TU1pT0xUdVZHUk1rOTN0c1ZsTWVCdGZSZHNKcGg1eDA1RVRROHBDcX
 c4di91CjBacDdvSC9jb0JnTU1OSFRxRlJQWVB2U0ZIOUU2cktrMlg5bGsrYmRFZmhsRzVXY2kxY
 jdURkk5M1FCcWoxTUMKVWRIQWZIamdLRWRHbWZ1VC9ybHBPQnZVdVBwU0RZQ0RSVWp4U3M4Lzlj
 bTFDelA0eElSWGYreUZ6aWNwTmNiSQpydm5IMFpXY3pBNzkwQ1lnN0txY3F3S3Yxc2l1YVZ0eWV
 GNFRLODNiZ1RDMGN3UWc5Wk40aFRCU2wxcXJGN1NuCkRqVTZZdz09Cj1aTkJICi0tLS0tRU5EIF
 BHUCBNRVNTQUdFLS0tLS0K
X-Developer-Key: i=manos.pitsidianakis@linaro.org; a=openpgp;
 fpr=7C721DF9DB3CC7182311C0BF68BC211D47B421E1
Received-SPF: pass client-ip=2a00:1450:4864:20::52c;
 envelope-from=manos.pitsidianakis@linaro.org; helo=mail-ed1-x52c.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Add stub definition of memory_order enum in wrapper.h.

Creating Rust bindings from C code is done by passing the wrapper.h
header to `bindgen`. This fails when library dependencies that use
compiler headers are enabled, and the libclang that bindgen detects does
not match the expected clang version. So far this has only been observed
with the memory_order enum symbols from stdatomic.h. If we add the enum
definition to wrapper.h ourselves, the error does not happen.

Before this commit, if the mismatch happened the following error could
come up:

  /usr/include/liburing/barrier.h:72:10: error: use of undeclared identifier 'memory_order_release'
  /usr/include/liburing/barrier.h:75:9: error: use of undeclared identifier 'memory_order_acquire'
  /usr/include/liburing/barrier.h:75:9: error: use of undeclared identifier 'memory_order_acquire'
  /usr/include/liburing/barrier.h:68:9: error: use of undeclared identifier 'memory_order_relaxed'
  /usr/include/liburing/barrier.h:65:17: error: use of undeclared identifier 'memory_order_relaxed'
  /usr/include/liburing/barrier.h:75:9: error: use of undeclared identifier 'memory_order_acquire'
  /usr/include/liburing/barrier.h:75:9: error: use of undeclared identifier 'memory_order_acquire'
  /usr/include/liburing/barrier.h:72:10: error: use of undeclared identifier 'memory_order_release'
  panicked at [..]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-cli-0.70.1/main.rs:45:36:
  Unable to generate bindings

To fix this (on my system) I would have to export CLANG_PATH and
LIBCLANG_PATH:

  export CLANG_PATH=/bin/clang-17
  export LIBCLANG_PATH=/usr/lib/llvm-17/lib

With these changes applied, bindgen is successful with both the
environment variables set and unset.

Since we're not using those symbols in the bindings (they are only used
by dependencies) this does not affect the generated bindings in any way.

Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
---
Changes in v2:
- Restored warning print in `configure` script (thanks Paolo and Junjie)
- Link to v1: https://lore.kernel.org/r/20241015-rust-wrapper-stdatomic-v1-1-f22c0bd31140@linaro.org
---
 rust/wrapper.h | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

diff --git a/rust/wrapper.h b/rust/wrapper.h
index 77e40213efb686d23f6b768b78602e4337623280..285d0eb6ad01e227a82f13e17c79390b4c34d37e 100644
--- a/rust/wrapper.h
+++ b/rust/wrapper.h
@@ -30,6 +30,23 @@
  * in order to generate C FFI compatible Rust bindings.
  */

+#ifndef __CLANG_STDATOMIC_H
+#define __CLANG_STDATOMIC_H
+/*
+ * Fix potential missing stdatomic.h error in case bindgen does not insert the
+ * correct libclang header paths on its own. We do not use stdatomic.h symbols
+ * in QEMU code, so it's fine to declare dummy types instead.
+ */
+typedef enum memory_order {
+  memory_order_relaxed,
+  memory_order_consume,
+  memory_order_acquire,
+  memory_order_release,
+  memory_order_acq_rel,
+  memory_order_seq_cst,
+} memory_order;
+#endif /* __CLANG_STDATOMIC_H */
+
 #include "qemu/osdep.h"
 #include "qemu/module.h"
 #include "qemu-io.h"

---
base-commit: cea8ac78545a83e1f01c94d89d6f5a3f6b5c05d2
change-id: 20241015-rust-wrapper-stdatomic-18d58292c243

--
γαῖα πυρί μιχθήτω

Signed-off-by: GitHub Actions Bot <bot@github.com>