accel/tcg: Include missing 'exec/translation-block.h' header
TB compile flags are defined in "exec/translation-block.h".
Include it in order to avoid when refactoring:

  accel/tcg/tcg-accel-ops.c:62:36: error: use of undeclared identifier 'CF_CLUSTER_SHIFT'
     62 |     cflags = cpu->cluster_index << CF_CLUSTER_SHIFT;
        |                                    ^
  accel/tcg/tcg-accel-ops.c:64:26: error: use of undeclared identifier 'CF_PARALLEL'
     64 |     cflags |= parallel ? CF_PARALLEL : 0;
        |                          ^
  accel/tcg/tcg-accel-ops.c:65:34: error: use of undeclared identifier 'CF_USE_ICOUNT'
     65 |     cflags |= icount_enabled() ? CF_USE_ICOUNT : 0;
        |                                  ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>