linux-user: Add missing mmap include
error: use of undeclared identifier 'MAP_FIXED_NOREPLACE'

Signed-off-by: Patrick Leis <venture@google.com>
Signed-off-by: Peter Foley <pefoley@google.com>