cocoa: Remove deprecated CVDisplayLinkCreateWithCGDisplay() calls
When building on macOS 15 we get:

../../ui/cocoa.m:662:14: error: 'CVDisplayLinkCreateWithCGDisplay' is deprecated:
    first deprecated in macOS 15.0
    - use NSView.displayLink(target:selector:), NSWindow.displayLink(target:selector:),
      or NSScreen.displayLink(target:selector:)
    [-Werror,-Wdeprecated-declarations]
  662 |         if (!CVDisplayLinkCreateWithCGDisplay(display, &displayLink)) {
      |              ^

Instead get the refresh rate from either CGDisplayModeGetRefreshRate or IOKit,
following the model of https://github.com/gwm17/glfw/commit/4ec7daf3e92.

Resolves: https://gitlab.com/qemu-project/qemu/-/issues/2575
Cc: Philippe Mathieu-Daudé <philmd@linaro.org>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>