[PULL 00/31] Next patches
https://lore.kernel.org/qemu-devel/20251223142959.1460293-1-peterx@redhat.com

---

From: Peter Xu <peterx@redhat.com>
To: qemu-devel@nongnu.org
Cc: Fabiano Rosas <farosas@suse.de>,
	Peter Xu <peterx@redhat.com>
Subject: [PULL 00/31] Next patches
Date: Tue, 23 Dec 2025 09:29:28 -0500
Message-ID: <20251223142959.1460293-1-peterx@redhat.com>
X-Mailer: git-send-email 2.50.1
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=170.10.133.124; envelope-from=peterx@redhat.com;
 helo=us-smtp-delivery-124.mimecast.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_HIGH=-0.001,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, RCVD_IN_MSPIKE_H3=0.001, RCVD_IN_MSPIKE_WL=0.001,
 RCVD_IN_VALIDITY_RPBL_BLOCKED=0.001, RCVD_IN_VALIDITY_SAFE_BLOCKED=0.001,
 SPF_HELO_PASS=-0.001, SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit 8dd5bceb2f9cc58481e9d22355a8d998220896de:

  Open 11.0 development tree (2025-12-23 14:45:38 +1100)

are available in the Git repository at:

  https://gitlab.com/peterx/qemu.git tags/next-pull-request

for you to fetch changes up to bcb411a005fdf39b76e99c14f3618c7b70f7774d:

  MAINTAINERS: remove David from "Memory API" section (2025-12-23 09:27:02 -0500)

----------------------------------------------------------------
memory + migration pull

- Pawel's misc fixes to mapped-ram when x-ignore-share is enabled
- Peter's series to cleanup migration error reporting
- Peter's added debug property for x-ignore-shared
- Part of Fabiano's series on unify capabilities and parameters
- Chuang's log_clear optimization on unaligned ramblocks
- Maintainer file update from Ben (CPR++) and David (MemoryAPI-)

----------------------------------------------------------------

Ben Chaney (1):
  MAINTAINERS: Update reviewers for CPR

Chuang Xu (1):
  migration: merge fragmented clear_dirty ioctls

David Hildenbrand (Red Hat) (1):
  MAINTAINERS: remove David from "Memory API" section

Fabiano Rosas (15):
  migration: Fix leak of block_bitmap_mapping
  migration: Fix leak of cpr_exec_command
  migration: Add a qdev property for StrOrNull
  tests/qtest/migration: Add a NULL parameters test for TLS
  migration: Normalize tls arguments
  migration: Remove MigrateSetParameters
  qapi/migration: Don't document MigrationParameter
  migration: Run a post update routine after setting parameters
  migration: Add a flag to track block-bitmap-mapping input
  migration: Remove checks for s->parameters has_* fields
  migration: Do away with usage of QERR_INVALID_PARAMETER_VALUE
  migration: Extract code to mark all parameters as present
  migration: Use QAPI_CLONE_MEMBERS in query_migrate_parameters
  tests/qtest/migration: Pass MigrateCommon into test functions
  tests/qtest/migration: Pass MigrateStart into cancel tests

Markus Armbruster (1):
  error: Poison g_autoptr(Error) to prevent its use

Pawel Zmarzly (4):
  migration: fix parsing snapshots with x-ignore-shared flag
  migration: Fix writing mapped_ram + ignore_shared snapshots
  scripts/analyze-migration: Rename RAM_SAVE_FLAG_COMPRESS to
    RAM_SAVE_FLAG_ZERO
  scripts/analyze-migration: Support mapped-ram snapshot format

Peter Xu (8):
  migration: Use explicit error_free() instead of g_autoptr
  Revert "error: define g_autoptr() cleanup function for the Error type"
  migration: Make migration_connect_set_error() own the error
  migration: Make multifd_send_set_error() own the error
  migration: Make multifd_recv_terminate_threads() own the error
  migration: Replace migrate_set_error() with migrate_error_propagate()
  migration: Use error_propagate() in migrate_error_propagate()
  migration/options: Add x-ignore-shared

 MAINTAINERS                               |   3 +-
 qapi/migration.json                       | 395 +---------------
 qapi/pragma.json                          |   1 +
 include/qapi/error.h                      |  20 +-
 include/system/physmem.h                  |   7 +-
 migration/migration.h                     |   9 +-
 migration/options.h                       |   1 +
 tests/qtest/migration/migration-qmp.h     |   1 +
 tests/qtest/migration/migration-util.h    |   8 +-
 accel/tcg/cputlb.c                        |   5 +-
 migration/channel.c                       |   1 -
 migration/cpr-exec.c                      |   5 +-
 migration/migration-hmp-cmds.c            |  13 +-
 migration/migration.c                     |  59 ++-
 migration/multifd-device-state.c          |   6 +-
 migration/multifd.c                       |  30 +-
 migration/options.c                       | 525 ++++++++++++----------
 migration/page_cache.c                    |   6 +-
 migration/postcopy-ram.c                  |   5 +-
 migration/ram.c                           | 102 +++--
 migration/savevm.c                        |  18 +-
 migration/tls.c                           |   2 +-
 system/memory.c                           |   2 +-
 system/physmem.c                          |  48 +-
 tests/qtest/migration/compression-tests.c | 131 +++---
 tests/qtest/migration/cpr-tests.c         |  75 ++--
 tests/qtest/migration/file-tests.c        | 202 ++++-----
 tests/qtest/migration/migration-qmp.c     |   9 +
 tests/qtest/migration/migration-util.c    |  26 +-
 tests/qtest/migration/misc-tests.c        | 112 ++---
 tests/qtest/migration/postcopy-tests.c    |  82 ++--
 tests/qtest/migration/precopy-tests.c     | 373 +++++++--------
 tests/qtest/migration/tls-tests.c         | 499 ++++++++++----------
 scripts/analyze-migration.py              |  72 ++-
 34 files changed, 1282 insertions(+), 1571 deletions(-)

--
2.50.1

Signed-off-by: GitHub Actions Bot <bot@github.com>