[PULL 00/16] Misc HW & Memory API patches for 2026-02-02
https://lore.kernel.org/qemu-devel/20260202212019.94205-1-philmd@linaro.org

---

From: =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@linaro.org>
To: qemu-devel@nongnu.org
Subject: [PULL 00/16] Misc HW & Memory API patches for 2026-02-02
Date: Mon,  2 Feb 2026 22:20:03 +0100
Message-ID: <20260202212019.94205-1-philmd@linaro.org>
X-Mailer: git-send-email 2.52.0
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2a00:1450:4864:20::42e;
 envelope-from=philmd@linaro.org; helo=mail-wr1-x42e.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: qemu development <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit 587f4a1805c83a4e1d59dd43cb14e0a834843d1d:

  python: fix msys64 wheel directory specification (2026-02-02 16:46:40 +1000)

are available in the Git repository at:

  https://github.com/philmd/qemu.git tags/hw-misc-20260202

for you to fetch changes up to d8316b64dfbb4fdb706f20c3b42fd9bcf70b0cdc:

  monitor: Reduce target-specific methods (2026-02-02 22:14:51 +0100)

Ignoring this checkpatch.pl error:

  ERROR: unnecessary whitespace before a quoted newline
  #85: FILE: tests/unit/test-cutils.c:3685:
  +            "s is \n";

----------------------------------------------------------------
Misc HW & memory API patches

- Add unit test for qemu_hexdump()
- Remove legacy native endianness API uses on the Alpha target
- Remove unused memory_region_init_rom_device_nomigrate()
- Fix use-after-free in NvmeNamespace "bootindex" suffix
- Correct documentation of SCSI Rotation Rate field
- Make iotlb_to_section() work with non-CPU AddressSpaces
- Reduce few monitor target-specific methods
----------------------------------------------------------------

Akihiko Odaki (1):
  hw/nvme: Fix bootindex suffix use-after-free

Alberto Garcia (1):
  hw/ide, scsi-disk: Fix typo on the rotation_rate documentation

BALATON Zoltan (2):
  memory: Remove memory_region_init_rom_device_nomigrate()
  memory: Add internal memory_region_set_ops helper function

Jim Shu (3):
  accel/tcg: Send the CPUTLBEntryFull struct into io_prepare()
  accel/tcg: Fix iotlb_to_section() for different AddressSpace
  system/physmem: Remove the assertion of page-aligned section number

Philippe Mathieu-Daudé (8):
  target/alpha: Use explicit little-endian LD/ST API
  target/alpha: Inline translator_ldl()
  configs/targets: Forbid Alpha to use legacy native endianness APIs
  target/alpha: Replace legacy ld_phys() -> address_space_ld()
  target/i386: Include missing 'svm.h' header in 'sev.h'
  monitor: Reduce target-specific declarations
  monitor: Add hmp_cmds_for_target() helper
  monitor: Reduce target-specific methods

Vladimir Sementsov-Ogievskiy (1):
  tests/unit: add unit test for qemu_hexdump()

 docs/devel/memory.rst                         |  1 -
 configs/targets/alpha-linux-user.mak          |  2 +
 configs/targets/alpha-softmmu.mak             |  2 +
 .../memory-region-housekeeping.cocci          |  8 ---
 hw/nvme/nvme.h                                |  1 +
 include/accel/tcg/iommu.h                     | 15 -----
 include/exec/cputlb.h                         |  4 +-
 include/hw/core/cpu.h                         | 17 ++---
 include/hw/ide/ide-dev.h                      |  2 +-
 include/hw/misc/mos6522.h                     |  2 -
 include/monitor/hmp-target.h                  | 14 ----
 include/monitor/hmp.h                         | 13 ++++
 include/system/memory.h                       | 27 --------
 monitor/monitor-internal.h                    |  9 ++-
 target/i386/sev.h                             |  2 +
 accel/tcg/cputlb.c                            | 32 +++++----
 hw/i386/sgx-stub.c                            |  1 +
 hw/i386/sgx.c                                 |  1 +
 hw/nvme/ns.c                                  |  7 +-
 hw/scsi/scsi-disk.c                           |  2 +-
 monitor/hmp-cmds.c                            |  1 +
 monitor/hmp-target.c                          | 66 ++-----------------
 monitor/hmp.c                                 | 63 +++++++++++++++++-
 system/memory.c                               | 56 +++++++---------
 system/physmem.c                              | 31 ---------
 target/alpha/helper.c                         | 28 ++++----
 target/alpha/translate.c                      |  2 +-
 target/i386/cpu-apic.c                        |  1 +
 target/i386/sev-system-stub.c                 |  1 +
 target/i386/sev.c                             |  1 +
 target/m68k/monitor.c                         |  1 +
 target/riscv/monitor.c                        |  1 +
 tests/unit/test-cutils.c                      | 66 +++++++++++++++++++
 util/meson.build                              |  2 +-
 34 files changed, 239 insertions(+), 243 deletions(-)

--
2.52.0

Signed-off-by: GitHub Actions Bot <bot@github.com>