dump/dump: Include missing 'exec/memory.h' header
dump.c calls address_space_read() which is declared
in "exec/memory.h". Include it explicitly to avoid
when refactoring unrelated headers:

  dump/dump.c:1892:13: error: call to undeclared function 'address_space_read'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   1892 |             address_space_read(&address_space_memory, addr,
        |             ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>