[PULL 00/18] Misc HW patches for 2025-11-18
https://lore.kernel.org/qemu-devel/20251118190053.39015-1-philmd@linaro.org

---

From: =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@linaro.org>
To: qemu-devel@nongnu.org
Subject: [PULL 00/18] Misc HW patches for 2025-11-18
Date: Tue, 18 Nov 2025 20:00:35 +0100
Message-ID: <20251118190053.39015-1-philmd@linaro.org>
X-Mailer: git-send-email 2.51.0
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2a00:1450:4864:20::344;
 envelope-from=philmd@linaro.org; helo=mail-wm1-x344.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit 711a1ddf899bef577907a10db77475c8834da52f:

  Merge tag 'pull-10.2-maintainer-171125-2' of https://gitlab.com/stsquad/qemu into staging (2025-11-18 09:18:23 +0100)

are available in the Git repository at:

  https://github.com/philmd/qemu.git tags/hw-misc-20251118

for you to fetch changes up to de285aa9076841c618d068f7b838e312fc8b26c6:

  ebpf: Make ebpf_rss_load() return value consistent with @errp (2025-11-18 19:59:36 +0100)

Ignoring following checkpatch error:

  ERROR: line over 90 characters
  #26: FILE: scripts/checkpatch.pl:3205:
  +  ERROR("DEVICE_NATIVE_ENDIAN is not allowed, use DEVICE_LITTLE_ENDIAN or DEVICE_BIG_ENDIAN instead\n" . $herecurr);

----------------------------------------------------------------
Misc HW patches

- Re-enable xenpvh machine in qemu-system-arm/aarch64 binaries
- Correct Xilinx Zynq DMA Devcfg registers range size
- Correct ACCEL_KERNEL_GSI_IRQFD_POSSIBLE typo
- Allow for multiple CHR_EVENT_CLOSED events in QTest framework
- Fix ACMD41 state machine for SD cards in SPI mode
- Avoid confusing address calculation around eMMC RPMB HMAC
- Fix a pair of build failures on Solaris (guest-agent and RDMA migration)
- Correct QOM parent of LASI south bridge
- Clarify MIPS / PPC 32-bit hosts removal in documentation
- Prevent further uses of DEVICE_NATIVE_ENDIAN definition
- Fix Error uses in eBPF
- Update David Hildenbrand's email address
----------------------------------------------------------------

Bin Meng (2):
  hw/sd: Fix incorrect idle state reporting in R1 response for SPI mode
  hw/sd: Fix ACMD41 state machine in SPI mode

Cédric Le Goater (1):
  hw/intc/ioapic: Fix ACCEL_KERNEL_GSI_IRQFD_POSSIBLE typo

David Hildenbrand (Red Hat) (1):
  MAINTAINERS: Update David Hildenbrand's email address

Djordje Todorovic (1):
  scripts/checkpatch: Check DEVICE_NATIVE_ENDIAN

Jan Kiszka (1):
  hw/sd/sdcard: Avoid confusing address calculation in rpmb_calc_hmac

Markus Armbruster (3):
  ebpf: Fix stubs to set an error when they return failure
  ebpf: Clean up useless error check in ebpf_rss_set_all()
  ebpf: Make ebpf_rss_load() return value consistent with @errp

Peter Maydell (1):
  system/qtest.c: Allow for multiple CHR_EVENT_CLOSED events

Philippe Mathieu-Daudé (7):
  hw/arm: Re-enable xenpvh machine in qemu-system-arm/aarch64 binaries
  qga/commands: Include proper Solaris header for getloadavg()
  hw/southbridge/lasi: Correct LasiState parent
  buildsys: Remove dead 'mips' entry in supported_cpus[] array
  migration/rdma: Check ntohll() availability with meson
  docs: Correct release of MIPS deprecations / removals
  docs: Mention 32-bit PPC host as removed

Yannick Voßen (1):
  hw/dma/zynq-devcfg: Fix register memory

 MAINTAINERS                     | 18 +++++++++---------
 docs/about/deprecated.rst       |  2 +-
 docs/about/removed-features.rst |  7 ++++++-
 meson.build                     |  3 ++-
 include/hw/misc/lasi.h          |  4 ++--
 ebpf/ebpf_rss-stub.c            |  4 +++-
 ebpf/ebpf_rss.c                 | 10 +++-------
 hw/arm/xen-pvh.c                |  2 ++
 hw/dma/xlnx-zynq-devcfg.c       |  2 +-
 hw/intc/ioapic.c                |  4 ++--
 hw/net/virtio-net.c             |  4 +---
 hw/sd/sd.c                      | 33 +++++++++++++++++++--------------
 migration/rdma.c                |  4 +---
 qga/commands-posix.c            |  3 +++
 system/qtest.c                  |  4 ++++
 .mailmap                        |  1 +
 scripts/checkpatch.pl           |  4 ++++
 17 files changed, 64 insertions(+), 45 deletions(-)

--
2.51.0

Signed-off-by: GitHub Actions Bot <bot@github.com>