[PATCH for-11.0 0/5] some improvements around error reporting
https://lore.kernel.org/qemu-devel/20251127173352.283731-1-vsementsov@yandex-team.ru

---

From: Vladimir Sementsov-Ogievskiy <vsementsov@yandex-team.ru>
To: dave@treblig.org,
	armbru@redhat.com
Cc: pbonzini@redhat.com, marcandre.lureau@redhat.com, qemu-devel@nongnu.org,
 vsementsov@yandex-team.ru
Subject: [PATCH for-11.0 0/5] some improvements around error reporting
Date: Thu, 27 Nov 2025 20:33:47 +0300
Message-ID: <20251127173352.283731-1-vsementsov@yandex-team.ru>
X-Mailer: git-send-email 2.48.1
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=178.154.239.136;
 envelope-from=vsementsov@yandex-team.ru; helo=forwardcorp1b.mail.yandex.net
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_VALIDITY_RPBL_BLOCKED=0.001, RCVD_IN_VALIDITY_SAFE_BLOCKED=0.001,
 SPF_HELO_NONE=0.001, SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Hi all. The main thing I wanted to do is to enable timestamps
for errer_report() and friends when QMP monitor is active.
Analyzing logs without timestamps is painful.

And some enhancements here and there around.

Vladimir Sementsov-Ogievskiy (5):
  ui/vnc: don't use of error_printf_unless_qmp()
  monitor: remove unused error_printf_unless_qmp() function
  monitor: rework monitor_cur_is_qmp() into monitor_cur_is_hmp()
  error: print error_report timestamp when QMP monitor is active
  error-report: fix doc for vreport()

 include/monitor/monitor.h      |  5 +----
 monitor/monitor.c              | 30 +++---------------------------
 stubs/error-printf.c           |  5 -----
 stubs/monitor-core.c           |  5 +++++
 tests/unit/test-util-sockets.c |  1 +
 ui/vnc.c                       |  9 ++++-----
 util/error-report.c            | 25 +++++++++++++++----------
 7 files changed, 29 insertions(+), 51 deletions(-)

--
2.48.1

Signed-off-by: GitHub Actions Bot <bot@github.com>