target/i386/helper: Include missing 'exec/translation-block.h' header
TB compile flags are defined in "exec/translation-block.h".
Include it in order to avoid when refactoring:

  target/i386/helper.c:536:28: error: use of undeclared identifier 'CF_PCREL'
    536 |     if (tcg_cflags_has(cs, CF_PCREL)) {
        |                            ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>