system/watchpoint: Include missing 'exec/cpu-all.h' header
TARGET_PAGE_MASK is defined in "exec/cpu-all.h".
Include it in order to avoid when refactoring:

  system/watchpoint.c:52:24: error: use of undeclared identifier 'TARGET_PAGE_MASK'
     52 |     in_page = -(addr | TARGET_PAGE_MASK);
        |                        ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>