[PULL 00/38] Accelerators & CPU patches for 2025-03-09
https://lore.kernel.org/qemu-devel/20250309175207.43828-1-philmd@linaro.org

---

From: =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@linaro.org>
To: qemu-devel@nongnu.org
Subject: [PULL 00/38] Accelerators & CPU patches for 2025-03-09
Date: Sun,  9 Mar 2025 18:51:29 +0100
Message-ID: <20250309175207.43828-1-philmd@linaro.org>
X-Mailer: git-send-email 2.47.1
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2a00:1450:4864:20::42d;
 envelope-from=philmd@linaro.org; helo=mail-wr1-x42d.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit d9a4282c4b690e45d25c2b933f318bb41eeb271d:

  Merge tag 'pull-tcg-20250308' of https://gitlab.com/rth7680/qemu into staging (2025-03-09 11:45:00 +0800)

are available in the Git repository at:

  https://github.com/philmd/qemu.git tags/accel-cpus-20250309

for you to fetch changes up to 8ff6ff09b9890ba390395d7510eca1025f7284df:

  MAINTAINERS: Consolidate core exec/vCPU handling section (2025-03-09 17:00:47 +0100)

----------------------------------------------------------------
Generic CPUs / accelerators patch queue

- Reduce "exec/tb-flush.h" inclusion on linux-user
- Consider alignment in bsd-user's mmap_find_vma()
- Unify MMAP common user emulation API
- Simplify cpu-target.c further
- Prefer cached CpuClass over CPU_GET_CLASS() macro
- Restrict CPU has_work() handlers to system emulation
- Consolidate core exec/vCPU section in MAINTAINERS

Following spurious checkpatch error deliberately ignored:

  8/38 Checking commit e27fa95fb9d1 (accel: Prefer cached CpuClass over CPU_GET_CLASS() macro)
  ERROR: space prohibited after that '&&' (ctx:ExW)
  #112: FILE: accel/tcg/watchpoint.c:120:
  +                && cpu->cc->tcg_ops->debug_check_watchpoint
                  ^

  total: 1 errors, 0 warnings, 74 lines checked

----------------------------------------------------------------

Philippe Mathieu-Daudé (38):
  linux-user: Only include 'exec/tb-flush.h' header when necessary
  bsd-user: Always use mmap_find_vma_aligned() in target_mmap()
  bsd-user: Propagate alignment argument to mmap_find_vma()
  user: Extract common MMAP API to 'user/mmap.h'
  cpus: Register VMState per user / system emulation
  cpus: Build cpu_exec_[un]realizefn() methods once
  cpus: Prefer cached CpuClass over CPU_GET_CLASS() macro
  accel: Prefer cached CpuClass over CPU_GET_CLASS() macro
  user: Prefer cached CpuClass over CPU_GET_CLASS() macro
  disas: Prefer cached CpuClass over CPU_GET_CLASS() macro
  gdbstub: Prefer cached CpuClass over CPU_GET_CLASS() macro
  hw/acpi: Prefer cached CpuClass over CPU_GET_CLASS() macro
  target/arm: Prefer cached CpuClass over CPU_GET_CLASS() macro
  cpus: Restrict cpu_has_work() to system emulation
  cpus: Un-inline cpu_has_work()
  cpus: Introduce SysemuCPUOps::has_work() handler
  target/alpha: Move has_work() from CPUClass to SysemuCPUOps
  target/arm: Move has_work() from CPUClass to SysemuCPUOps
  target/avr: Move has_work() from CPUClass to SysemuCPUOps
  target/hexagon: Remove CPUClass:has_work() handler
  target/hppa: Move has_work() from CPUClass to SysemuCPUOps
  target/i386: Move has_work() from CPUClass to SysemuCPUOps
  target/loongarch: Move has_work() from CPUClass to SysemuCPUOps
  target/m68k: Move has_work() from CPUClass to SysemuCPUOps
  target/microblaze: Move has_work() from CPUClass to SysemuCPUOps
  target/mips: Move has_work() from CPUClass to SysemuCPUOps
  target/openrisc: Move has_work() from CPUClass to SysemuCPUOps
  target/ppc: Move has_work() from CPUClass to SysemuCPUOps
  target/riscv: Move has_work() from CPUClass to SysemuCPUOps
  target/rx: Move has_work() from CPUClass to SysemuCPUOps
  target/s390x: Restrict I/O handler installers to system emulation
  target/s390x: Move has_work() from CPUClass to SysemuCPUOps
  target/sh4: Move has_work() from CPUClass to SysemuCPUOps
  target/sparc: Move has_work() from CPUClass to SysemuCPUOps
  target/tricore: Move has_work() from CPUClass to SysemuCPUOps
  target/xtensa: Move has_work() from CPUClass to SysemuCPUOps
  cpus: Remove CPUClass::has_work() handler
  MAINTAINERS: Consolidate core exec/vCPU handling section

 MAINTAINERS                      |  14 +--
 bsd-user/bsd-mem.h               |   4 +-
 bsd-user/qemu.h                  |  12 +--
 include/accel/tcg/cpu-ops.h      |   2 +-
 include/hw/core/cpu.h            |  35 +++---
 include/hw/core/sysemu-cpu-ops.h |   4 +
 include/user/mmap.h              |  32 ++++++
 linux-user/alpha/target_proc.h   |   2 +-
 linux-user/user-internals.h      |   1 -
 linux-user/user-mmap.h           |  19 +---
 target/i386/cpu.h                |   4 +-
 target/mips/internal.h           |   4 +-
 target/riscv/internals.h         |   4 +-
 target/s390x/s390x-internal.h    |   5 +
 accel/accel-target.c             |  12 +--
 accel/tcg/tcg-accel-ops.c        |   3 +-
 accel/tcg/translate-all.c        |   2 +-
 accel/tcg/watchpoint.c           |   9 +-
 bsd-user/mmap.c                  |  17 +--
 bsd-user/signal.c                |   4 +-
 cpu-common.c                     |  10 +-
 cpu-target.c                     | 146 -------------------------
 disas/disas-common.c             |   5 +-
 gdbstub/gdbstub.c                |  26 ++---
 gdbstub/system.c                 |   7 +-
 gdbstub/user-target.c            |   6 +-
 gdbstub/user.c                   |   7 +-
 hw/acpi/cpu.c                    |   4 +-
 hw/acpi/cpu_hotplug.c            |   3 +-
 hw/core/cpu-common.c             |  47 +++++---
 hw/core/cpu-system.c             | 179 +++++++++++++++++++++++++------
 hw/core/cpu-user.c               |  17 +++
 linux-user/mmap.c                |   1 +
 linux-user/signal.c              |   4 +-
 linux-user/syscall.c             |   1 +
 target/alpha/cpu.c               |   4 +-
 target/arm/cpu.c                 |   7 +-
 target/arm/tcg/cpu-v7m.c         |   3 +-
 target/avr/cpu.c                 |   2 +-
 target/hexagon/cpu.c             |   6 --
 target/hppa/cpu.c                |   4 +-
 target/i386/cpu.c                |   8 +-
 target/loongarch/cpu.c           |   8 +-
 target/m68k/cpu.c                |   4 +-
 target/microblaze/cpu.c          |   4 +-
 target/mips/cpu.c                |   4 +-
 target/openrisc/cpu.c            |   4 +-
 target/ppc/cpu_init.c            |   4 +-
 target/riscv/cpu.c               |   8 +-
 target/rx/cpu.c                  |   2 +-
 target/s390x/cpu-system.c        |  18 ++++
 target/s390x/cpu.c               |  18 ----
 target/s390x/interrupt.c         |   8 +-
 target/sh4/cpu.c                 |   4 +-
 target/sparc/cpu.c               |   4 +-
 target/tricore/cpu.c             |   2 +-
 target/xtensa/cpu.c              |  12 +--
 57 files changed, 384 insertions(+), 406 deletions(-)
 create mode 100644 include/user/mmap.h

--
2.47.1

Signed-off-by: GitHub Actions Bot <bot@github.com>