target/rx/cpu: Include missing 'exec/translation-block.h' header
The TranslationBlock structure is declared in
"exec/translation-block.h", along with the TB
compile flag definitions. Include the header
in order to avoid when refactoring:

  target/rx/cpu.c:50:42: error: use of undeclared identifier 'CF_PCREL'
     50 |     tcg_debug_assert(!tcg_cflags_has(cs, CF_PCREL));
        |                                          ^
  target/rx/cpu.c:51:21: error: incomplete definition of type 'struct TranslationBlock'
     51 |     cpu->env.pc = tb->pc;
        |                   ~~^
  include/qemu/typedefs.h:116:16: note: forward declaration of 'struct TranslationBlock'
    116 | typedef struct TranslationBlock TranslationBlock;
        |                ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>