[RFC PATCH-for-10.2?] tests/tcg: Skip syscall catchpoint test if
https://lore.kernel.org/qemu-devel/20251203084743.60753-1-philmd@linaro.org

---

From: =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@linaro.org>
To: qemu-devel@nongnu.org
Cc: =?UTF-8?q?Alex=20Benn=C3=A9e?= <alex.bennee@linaro.org>,
 Gustavo Romero <gustavo.romero@linaro.org>,
 =?UTF-8?q?Philippe=20Mathieu-Daud=C3=A9?= <philmd@linaro.org>
Subject: [RFC PATCH-for-10.2?] tests/tcg: Skip syscall catchpoint test if
 pipe2() syscall not available
Date: Wed,  3 Dec 2025 09:47:43 +0100
Message-ID: <20251203084743.60753-1-philmd@linaro.org>
X-Mailer: git-send-email 2.51.0
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Received-SPF: pass client-ip=2a00:1450:4864:20::32c;
 envelope-from=philmd@linaro.org; helo=mail-wm1-x32c.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

Avoid the following errors testing i386 and ppc64:

  $ make check-tcg
  ...
    TEST    hitting a syscall catchpoint on i386
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-i386: QEMU: Terminated via GDBstub
  ...
    TEST    hitting a syscall catchpoint on ppc64
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-ppc64: QEMU: Terminated via GDBstub
  ...
    TEST    hitting a syscall catchpoint on ppc64le
  warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
  Traceback (most recent call last):
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 53, in <module>
      main(run_test)
    File "tests/guest-debug/test_gdbstub.py", line 53, in main
      test()
    File "tests/tcg/multiarch/gdbstub/catch-syscalls.py", line 22, in run_test
      gdb.execute("catch syscall pipe2 read")
  gdb.error: Unknown syscall name 'pipe2'.
  qemu-ppc64le: QEMU: Terminated via GDBstub
  make: Target 'check-tcg' not remade because of errors.

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
---
 tests/tcg/multiarch/gdbstub/catch-syscalls.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/tests/tcg/multiarch/gdbstub/catch-syscalls.py b/tests/tcg/multiarch/gdbstub/catch-syscalls.py
index ccce35902fb..5c654b63f56 100644
--- a/tests/tcg/multiarch/gdbstub/catch-syscalls.py
+++ b/tests/tcg/multiarch/gdbstub/catch-syscalls.py
@@ -22,7 +22,8 @@ def run_test():
         gdb.execute("catch syscall pipe2 read")
     except gdb.error as exc:
         exc_str = str(exc)
-        if "not supported on this architecture" in exc_str:
+        if "not supported on this architecture" in exc_str \
+                or if "Unknown syscall name 'pipe2'" in exc_str:
             print("SKIP: {}".format(exc_str))
             return
         raise
--
2.51.0

Signed-off-by: GitHub Actions Bot <bot@github.com>