[PULL 0/8] Error reporting patches for 2025-03-21
https://lore.kernel.org/qemu-devel/20250321145158.3896812-1-armbru@redhat.com

---

From: Markus Armbruster <armbru@redhat.com>
To: qemu-devel@nongnu.org
Cc: stefanha@redhat.com
Subject: [PULL 0/8] Error reporting patches for 2025-03-21
Date: Fri, 21 Mar 2025 15:51:50 +0100
Message-ID: <20250321145158.3896812-1-armbru@redhat.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Scanned-By: MIMEDefang 3.4.1 on 10.30.177.111
Received-SPF: pass client-ip=170.10.129.124; envelope-from=armbru@redhat.com;
 helo=us-smtp-delivery-124.mimecast.com
X-Spam_score_int: -23
X-Spam_score: -2.4
X-Spam_bar: --
X-Spam_report: (-2.4 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_HIGH=-0.332,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, RCVD_IN_MSPIKE_H5=0.001, RCVD_IN_MSPIKE_WL=0.001,
 RCVD_IN_VALIDITY_RPBL_BLOCKED=0.001, RCVD_IN_VALIDITY_SAFE_BLOCKED=0.001,
 SPF_HELO_NONE=0.001, SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

The following changes since commit 1dae461a913f9da88df05de6e2020d3134356f2e:

  Update version for v10.0.0-rc0 release (2025-03-18 10:18:14 -0400)

are available in the Git repository at:

  https://repo.or.cz/qemu/armbru.git tags/pull-error-2025-03-21

for you to fetch changes up to a725bc970e3091499be8be52798c21259f91b2cd:

  target/loongarch: Clean up virt_cpu_irq_init() error handling (2025-03-20 07:58:19 +0100)

----------------------------------------------------------------
Error reporting patches for 2025-03-21

----------------------------------------------------------------
Bibo Mao (4):
      target/loongarch: Fix error handling of KVM feature checks
      hw/loongarch/virt: Eliminate error_propagate()
      target/loongarch: Remove unnecessary temporary variable assignment
      target/loongarch: Clean up virt_cpu_irq_init() error handling

Markus Armbruster (4):
      cryptodev: Fix error handling in cryptodev_lkcf_execute_task()
      error: Strip trailing '\n' from an error string argument
      hw/xen: Fix xen_bus_realize() error handling
      hw/xen: Downgrade a xen_bus_realize() non-error to warning

 backends/cryptodev-lkcf.c         |  3 +++
 hw/loongarch/virt.c               | 39 +++++++++++++++------------------------
 hw/xen/xen-bus.c                  |  8 ++++----
 target/loongarch/kvm/kvm.c        |  8 ++++++--
 target/loongarch/tcg/tlb_helper.c |  5 ++---
 net/vmnet-common.m                |  2 +-
 6 files changed, 31 insertions(+), 34 deletions(-)

--
2.48.1

Signed-off-by: GitHub Actions Bot <bot@github.com>