error: print error_report timestamp when QMP monitor is active
We skip printing timestamp when _any_ monitor is active. But
then, in production (where QMP is usually used) we lack timestamps
in logs.

Let's go a bit further, and use same logic to detect HMP monitor
in the whole util/error-report.c like in error_vprintf().

Signed-off-by: Vladimir Sementsov-Ogievskiy <vsementsov@yandex-team.ru>