[PATCH] rust/bindings: allow unnecessary_transmutes (1.88)
https://lore.kernel.org/qemu-devel/20250703-rust_bindings_allow_unnecessary_transmutes-v1-1-692ca210d331@linaro.org

---

From: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
Date: Thu, 03 Jul 2025 17:20:22 +0300
Subject: [PATCH] rust/bindings: allow unnecessary_transmutes (1.88)
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
Message-Id: <20250703-rust_bindings_allow_unnecessary_transmutes-v1-1-692ca210d331@linaro.org>
X-B4-Tracking: v=1; b=H4sIAKWRZmgC/x3NQQrCMBBA0auUWRtIamrBq4iEtBnrQJ3KTKKW0
 rs3uHyb/zdQFEKFa7OB4IeUFq5wpwbGZ+QJDaVqaG3b2d6ejRTNYSBOxJOGOM/LNxRmHFE1yhq
 yRNZXyagmXZxPg+9cHz3U4FvwQb//7Hbf9wNQftURfAAAAA==
X-Change-ID: 20250703-rust_bindings_allow_unnecessary_transmutes-d614db4517a4
To: qemu-devel@nongnu.org
Cc: qemu-rust@nongnu.org, Paolo Bonzini <pbonzini@redhat.com>,
 Zhao Liu <zhao1.liu@intel.com>,
 Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
X-Mailer: b4 0.14.2
X-Developer-Signature: v=1; a=openpgp-sha256; l=1667;
 i=manos.pitsidianakis@linaro.org; h=from:subject:message-id;
 bh=qBnzFK2jzBx9ni4zlQZpeE9EoRu2AVMJDhHXnUF08bA=;
 b=LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpvd0VCYlFLUy9aQU5Bd0FLQVhjcHgzQi9mZ
 25RQWNzbVlnQm9acEd5YXhRYm8wandnZjVEcEVGZjhMajkyYUU0ClJkYWI1eGExTmxKN08yWXgx
 SmVKQWpNRUFBRUtBQjBXSVFUTVhCdE9SS0JXODRkd0hSQjNLY2R3ZjM0SjBBVUMKYUdhUnNnQUt
 DUkIzS2Nkd2YzNEowRi9ZRC85MGtQV09zMkdiVUpmd1NqaWNQcHhRV3dnMHpxNjF3MkN1RmRvYg
 o0NXNXeUdtdm9STDZSYmlGaE5lMVFGMmlMdGkwMWRLRG1PcSthUVpLeTV6MllBYjdkZy9lS24yS
 U1hQUgwTkYrCm1zam5tRzc0cGhjMm9KOG5SRjlQakt1QlRzcGhQUnJ1WlVGdDNlNnBoWWpBT2FQ
 SjVTcDVwbGRaVnNCaGdQZ24KRlgwUVN4bmVQWXloTTRGdjAvTStjKzRBR0YrL3BVMWdHdGdlVS9
 5c3UwNWZESHZXZUlZendYSi93YVlGUGhhRQpnazkwdEtMaUkxQkRpM21oZmduWnBEakVHWHN6bF
 k3UlZZWUlxWGsyNzZ6UTdQaFBEYWJCR2dWVHVXMzFKNnlkCkhjaWNEUWhQS0ZocTFXYkhXYk9QT
 WhtVzRFN2hSU0FsZWlQK2tsVTdkZWRzZTFHZ0JnNklUS0pvYzZud2gvUmUKR1c2K2g4bVROWjl5
 dUIzMzU4VU5oVmtneXZBa3BtRHRkSmFKZThodWNQbUk3SDRoR1Y4dkN3TDJHTUpEUnpvVApoSnV
 aaGFwcmNvQzlkREhYTmhqRzN1WldKK1JWalNPYkNJNG5ubmI2RUhWWjBYZWpCdzl3VEd0TURSdU
 ZHMm55CnZxR1E4ME94M3h4UHJONFNTUHJ4R2NlbzJYb3M5Mm5zR1pvaHdqSnEvR3dhSTFpbFhUZ
 k9KR0JpTnJCSkI2WGMKUWdPZVRxdEhNZTMxUkd6OHRLd2Z4d3VhK3JpUG9SaXVjd2FVZVNwazQ4
 eGtqeko4Tmw3blZ5dWt1aE5ETHI1KwpIYlQ1TXVQTHVtVUt4c2ZWamE4QlkybmxIQ1NWRXpYbEc
 0TVptVlZQN2Q5dGdxQnhjc2lUWlNNcGphM091cEFBCjN6Mmhndz09Cj1SVWZPCi0tLS0tRU5EIF
 BHUCBNRVNTQUdFLS0tLS0K
X-Developer-Key: i=manos.pitsidianakis@linaro.org; a=openpgp;
 fpr=7C721DF9DB3CC7182311C0BF68BC211D47B421E1
Received-SPF: pass client-ip=2a00:1450:4864:20::32a;
 envelope-from=manos.pitsidianakis@linaro.org; helo=mail-wm1-x32a.google.com
X-Spam_score_int: -20
X-Spam_score: -2.1
X-Spam_bar: --
X-Spam_report: (-2.1 / 5.0 requ) BAYES_00=-1.9, DKIM_SIGNED=0.1,
 DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 RCVD_IN_DNSWL_NONE=-0.0001, SPF_HELO_NONE=0.001,
 SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org
Sender: qemu-devel-bounces+qemu-devel=archiver.kernel.org@nongnu.org

This is a new lint introduced in Rust 1.88. It does not affect
compilation when using a previous version or our MSRV, 1.77. But with
1.88 compilation fails because we deny all warnings:

  error: unnecessary transmute
     --> rust/qemu-api/libqemu_api.rlib.p/structured/bindings.inc.rs:729:18
      |
  729 |         unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace this with: `u32::cast_signed(self._bitfield_1.get(0usize, 24u8) as u32)`
      |
      = note: `-D unnecessary-transmutes` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(unnecessary_transmutes)]`

Allow this lint, which even though it does not exist in previous
versions, it works because we allow for `unknown_lints` in
rust/Cargo.toml.

Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
---
 rust/qemu-api/src/bindings.rs | 1 +
 1 file changed, 1 insertion(+)

diff --git a/rust/qemu-api/src/bindings.rs b/rust/qemu-api/src/bindings.rs
index 057de4b6467c50ecc5acb6b51e6fde87ef5fa67f..3cdad0f0ec640880bc74a942bbcb303be4cda775 100644
--- a/rust/qemu-api/src/bindings.rs
+++ b/rust/qemu-api/src/bindings.rs
@@ -6,6 +6,7 @@
     non_camel_case_types,
     non_snake_case,
     non_upper_case_globals,
+    unnecessary_transmutes,
     unsafe_op_in_unsafe_fn,
     clippy::pedantic,
     clippy::restriction,

---
base-commit: c77283dd5d79149f4e7e9edd00f65416c648ee59
change-id: 20250703-rust_bindings_allow_unnecessary_transmutes-d614db4517a4

--
γαῖα πυρί μιχθήτω

Signed-off-by: GitHub Actions Bot <bot@github.com>